version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: rubrics_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - rubrics_network

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@postgres:5432/rubrics_db
      - SECRET_KEY=your-secret-key-here
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    volumes:
      - ./backend:/app
      - backend_uploads:/app/uploads
      - backend_results:/app/results
    depends_on:
      - postgres
    networks:
      - rubrics_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8000/api
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - rubrics_network

volumes:
  postgres_data:
  backend_uploads:
  backend_results:

networks:
  rubrics_network:
    driver: bridge